name: py36
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.13
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tensorflow=1.14.0=mkl_py36h2526735_0
  - tensorflow-base=1.14.0=mkl_py36h7ce6ba3_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-probability=0.7=py_2
 